### ISSUE TITLE
Redundant "strictly" word in exception message when DefaultInequalityStrictness = InequalityStrictness.Strict

### ISSUE THREAD

**Issue by XtroTheArctic** [postsharp/Metalama.Patterns#150]
I have this definition in my root Atesh.Metalama library.

```
using Metalama.Framework.Fabrics;
using Metalama.Patterns.Contracts;

namespace Atesh.Metalama;

class InequalityStrictnessFabric : TransitiveProjectFabric
{
    public override void AmendProject(IProjectAmender Amender) => Amender.ConfigureContracts(new() { DefaultInequalityStrictness = InequalityStrictness.Strict });
}
```

When I use this library in another test library where I test parameter validations on some of my methods, the exception message contains a redundant "strictly" word.

![image](https://github.com/user-attachments/assets/3984b301-89dc-4688-98aa-370c9cd41adc)

**Comment by gfraiteur** [comment]
Okay I will ignore this for now as a matter of preferences. If you want to change the exception message, you can [override the template](https://doc.postsharp.net/metalama/preview/patterns/contracts/configuring-contracts#example-translating-error-messages).
