### ISSUE TITLE
When the Range related aspects throw an exception, ArgumentOutOfRangeException.ActualValue is null but it should contain the actual value which was passed to the parameter.

### ISSUE THREAD

**Issue by XtroTheArctic** [postsharp/Metalama.Patterns#151]
I first posted this in a related ticket: https://github.com/postsharp/Metalama.Patterns/issues/13

**Comment by svick** [comment]
Thanks for the suggestion.

I wouldn't consider this to be a bug, setting the `ActualValue` is not a requirement and there are even many cases where .Net doesn't do it.

And you can override the default behavior of contracts by [writing custom `ContractTemplates`](https://doc.postsharp.net/metalama/patterns/contracts/configuring-contracts#customizing-the-exception-type-or-text).

But I also think improving the default behavior is a good idea and it's not hard to change, so we should do it.

**Comment by XtroTheArctic** [comment]
Yes, please add if you can because that value is necessary in my unit tests.

We would not need to test the implementation official .NET methods but testing our own methods is very important. That's why we need the ActualValue. Thank you very much for considering.

**Comment by prochan2** [comment]
Hello, this issue has been fixed in Metalama 2024.2.16-rc.

**Comment by XtroTheArctic** [comment]
I confirm. Thank you!
